### PR TITLE
Add --insecure so curl commands work out of the box with default Elas…

### PR DESCRIPTION
**Pull request by tomchiverton**
…ticSearch Service clusters

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aetter** [comment]
Hi @tomchiverton, I don't encounter any issues with the command as-is. Are you getting different responses from the domain with and without the `--insecure` flag?

```
$ curl -XPUT my-test-domain/movies/movie/1 -d '{"director": "Burton, Tim", "genre": ["Comedy","Sci-Fi"], "year": 1996, "actor": ["Jack Nicholson","Pierce Brosnan","Sarah Jessica Parker"], "title": "Mars Attacks!"}' -H 'Content-Type: application/json'

{"_index":"movies","_type":"movie","_id":"1","_version":2,"result":"updated","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":14}
```

Andrew

**Comment by tomchiverton** [comment]
Yes, the TLS certificate is invalid.
Particularly, when following the recommendation to access VPC over a SSH port forward. 
-- 
Tom

**Comment by aetter** [comment]
Hi @tomchiverton, even using the SSH tunnel to connect to a VPC domain (which isn't applicable to the Getting Started walkthrough), I'm still not able to reproduce.

```
$ curl -XPUT https://localhost:9200/movies/movie/1 -d '{"director": "Burton, Tim", "genre": ["Comedy","Sci-Fi"], "year": 1996, "actor": ["Jack Nicholson","Pierce Brosnan","Sarah Jessica Parker"], "title": "Mars Attacks!"}' -H 'Content-Type: application/json'

{"_index":"movies","_type":"movie","_id":"1","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
```

If you post your OS, curl version, and the various commands and responses, I'll have more to go off of.

**Comment by tomchiverton** [comment]
The SSL certificate will not match against localhost when used over a tunnel in Firefox or Curl

```
tchiverton@noctua:~$ curl -XGET https://localhost:9200/my_index/_doc/pdf_text 
curl: (51) SSL: no alternative certificate subject name matches target host name 'localhost'
tchiverton@noctua:~$ 
```

screenshot_20181008_105555

**Comment by aetter** [comment]
Hi @tomchiverton, I'm still unable to reproduce, but I've added [a tip to the VPC file](https://github.com/awsdocs/amazon-elasticsearch-service-developer-guide/commit/fd3c713f0a9b70fafbee4ef97422b1a3ecfd4f7a#diff-8b6c37f50f335b4efdad8a7aad0ca68b) to try the `--insecure` flag if you encounter issue. The Getting Started file isn't the right place for this content, so I'm going to close out this PR.

**Pull request closed without merging**
